services:
  bot:
    build:
      context: .
#    restart: always
    depends_on:
      - telegram-bot-api
      - redis
    env_file:
      - .env
    volumes:
      - ./telegram-data/:/cozebot/telegram-data

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    expose:
      - '8081'
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=${TELEGRAM_LOCAL}
    volumes:
      - ./telegram-data:/var/lib/telegram-bot-api

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "4CEqaD0JL8gTM4XWVt8K"]
    expose:
      - '6379'
    volumes:
      - ./redisdata:/data

volumes:
  telegram-data:
